package dao;

import dao.mappers.IMapResultSetIntoEntity;
import dao.model.Kremacja;
import dao.uow.IUnitOfWork;
import java.sql.Connection;
import java.sql.SQLException;

public class KremacjaRepository extends RepositoryBase<Kremacja> {

    public KremacjaRepository(Connection connection, IMapResultSetIntoEntity<Kremacja> mapper, IUnitOfWork uow) {
        super(connection, mapper, uow);
    }

    @Override
    public String tableName() {
        return "Kremacje";
    }

    @Override
    public String createTableSql() {

        return "create table "
                + tableName()
                + " id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                + "id_zmarlego int ,"
                + "czy_skremowany boolean"
                + "FOREIGN KEY (id_zmarlego) REFERENCES Zmarli(ID))";
    }

    @Override
    public String insertSql() {
        return "insert into "
                + tableName()
                + " (id_zmarlego,czy_skremowany) "
                + "values (?,?) ";
    }

    @Override
    public String updateSql() {
        return "update "
                + tableName()
                + " set (id_zmarlego,czy_skremowany)= "
                + "(?,?) "
                + "where id=?";
    }

    @Override
    public void insertPrepare(Kremacja entity) throws SQLException {
        insert.setInt(1, entity.getIdZmarlego());
        insert.setBoolean(2, entity.isCzySkremowany());
    }

    @Override
    public void updatePrepare(Kremacja entity) throws SQLException {
        update.setInt(1, entity.getIdZmarlego());
        update.setBoolean(2, entity.isCzySkremowany());
        update.setInt(3, entity.getId());
    }

}
