
package dao;

import dao.mappers.IMapResultSetIntoEntity;
import dao.model.ZakupZnicza;
import dao.uow.IUnitOfWork;
import java.sql.Connection;
import java.sql.SQLException;


public class ZakupZniczaRepository extends RepositoryBase<ZakupZnicza>{

    public ZakupZniczaRepository(Connection connection, IMapResultSetIntoEntity<ZakupZnicza> mapper, IUnitOfWork uow) {
        super(connection, mapper, uow);
    }
    
    
    @Override
    public String tableName() {
        return "ZakupyZnicza";
    }

    @Override
    public String createTableSql() {


        return "create table "
                + tableName()
                + " id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                + " ilosc_zniczy int,"
                + " cena_za_sztuke int,"
                + " id_usera int,"
                + " id_zmarlego int,"
                + " FOREIGN KEY (id_zmarlego) REFERENCES Zmarli(ID),"
                + " FOREIGN KEY (id_usera) REFERENCES uzytkownicy(ID)"
                + ")";
    }

    @Override
    public String insertSql() {
        return "insert into "
                + tableName()
                + " (ilosc_zniczy,cena_za_sztuke,id_usera,id_zmarlego) "
                + "values (?,?,?,?) ";
    }

    @Override
    public String updateSql() {
        return "update "
                + tableName()
                + " set (ilosc_zniczy,cena_za_sztuke,id_usera,id_zmarlego)= "
                + "(?,?,?,?) "
                + "where id=?";
    }

    @Override
    public void insertPrepare(ZakupZnicza entity) throws SQLException {
        insert.setInt(1, entity.getIloscZniczy());
        insert.setInt(2, entity.getCenaZaSztuke());
        insert.setInt(3, entity.getIdUsera());
        insert.setInt(4, entity.getIdZmarlego());
    }

    @Override
    public void updatePrepare(ZakupZnicza entity) throws SQLException {
        update.setInt(1, entity.getIloscZniczy());
        update.setInt(2, entity.getCenaZaSztuke());
        update.setInt(3, entity.getIdUsera());
        update.setInt(4, entity.getIdZmarlego());
        update.setInt(5, entity.getId());
    }

    
    
    
}
