
package dao;

import dao.mappers.IMapResultSetIntoEntity;
import dao.model.Zmarly;
import dao.uow.IUnitOfWork;
import java.sql.Connection;
import java.sql.SQLException;


public class ZmarlyRepository extends RepositoryBase<Zmarly> {

    public ZmarlyRepository(Connection connection, IMapResultSetIntoEntity<Zmarly> mapper, IUnitOfWork uow) {
        super(connection, mapper, uow);
    }

    
    @Override
    public String tableName() {
        return "zmarli";
    }

    @Override
    public String createTableSql() {

        return "create table "
                + tableName()
                + "( id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                + " id_usera int,"
                + "data_smierci date ,"
                + "data_urodzenia date ,"
                + "imie varchar(20),"
                + "nazwisko varchar(20),"
                + "FOREIGN KEY (id_usera) REFERENCES uzytkownicy(ID))";
    }

    @Override
    public String insertSql() {
        return "insert into "
                + tableName()
                + " (id_usera,data_smierci,data_urodzenia,imie,nazwisko) "
                + "values (?,?,?,?,?) ";
    }

    @Override
    public String updateSql() {
        return "update "
                + tableName()
                + " set (id_usera,data_smierci,data_urodzenia,imie,nazwisko)= "
                + "(?,?,?,?,?) "
                + "where id=?";
    }

    @Override
    public void insertPrepare(Zmarly entity) throws SQLException {
        insert.setInt(1,entity.getIdUzytkownika());
        insert.setDate(2, entity.getDataSmierci());
        insert.setDate(3, entity.getDataUrodzenia());
        insert.setString(4,entity.getImie());
        insert.setString(5, entity.getNazwisko());
    }

    @Override
    public void updatePrepare(Zmarly entity) throws SQLException {
        update.setInt(1,entity.getIdUzytkownika());
        update.setDate(2, entity.getDataSmierci());
        update.setDate(3, entity.getDataUrodzenia());
        update.setString(4,entity.getImie());
        update.setString(5, entity.getNazwisko());
        update.setInt(6, entity.getId());
    }

}