package dao;

import dao.mappers.IMapResultSetIntoEntity;
import dao.model.Znicz;
import dao.uow.IUnitOfWork;
import java.sql.Connection;
import java.sql.SQLException;

public class ZniczRepository extends RepositoryBase<Znicz> {

    public ZniczRepository(Connection connection, IMapResultSetIntoEntity<Znicz> mapper, IUnitOfWork uow) {
        super(connection, mapper, uow);
    }

    @Override
    public String tableName() {
        return "znicze";
    }

    @Override
    public String createTableSql() {

        return "create table "
                + tableName()
                + " (id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                + " id_zmarlego int,"
                + " data_startu date,"
                + " data_zakonczenia date,"
                + "FOREIGN KEY (id_zmarlego) REFERENCES Zmarli(ID))";
    }

    @Override
    public String insertSql() {
        return "insert into "
                + tableName()
                + " (id_zmarlego,data_startu,data_zakonczenia) "
                + "values (?,?,?) ";
    }

    @Override
    public String updateSql() {
        return "update "
                + tableName()
                + " set (id_zmarlego,data_startu,data_zakonczenia)= "
                + "(?,?,?) "
                + "where id=?";
    }

    @Override
    public void insertPrepare(Znicz entity) throws SQLException {
        insert.setInt(1, entity.getIdZmarlego());
        insert.setDate(2, entity.getDataStartu());
        insert.setDate(3, entity.getDataZakonczenia());
    }

    @Override
    public void updatePrepare(Znicz entity) throws SQLException {
        update.setInt(1, entity.getIdZmarlego());
        update.setDate(2, entity.getDataStartu());
        update.setDate(3, entity.getDataZakonczenia());
        update.setInt(4, entity.getId());
    }

}
